# Generated by Django 3.2.3 on 2021-08-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tod',
            new_name='Todo',
        ),
    ]
